### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by arceus-jia** [ethereum/remix-ide#1033]
[downloadsolc] ✖ Install fail! Error: [downloadsolc@*] GET https://registry.npmjs.org/downloadsolc/latest response 404 status

If I ignore this, it shows
Error: Cannot find module '../../../../_is-buffer@1.1.6@is-buffer/index.js' from '/Users/arceus/Desktop/dapp/browser-solidity/node_modules/_core-util-is@1.0.2@core-util-is/lib'
after I run npm start.

My node version is 9.4.0, and my npm is version 5.6.0

Anyone have ideas? thanks a lot.

**Comment by Dracarys** [comment]
I got this error  too!

here is my console log:

```
> remix-solidity@0.0.8 postinstall /Users/xxxx/Documents/Ethereum/browser-solidity/node_modules/remix-solidity
> npm-run-all -ls downloadsolc

[downloadsolc] 
[downloadsolc] > remix-solidity@0.0.8 downloadsolc /Users/xxxx/Documents/Ethereum/browser-solidity/node_modules/remix-solidity
[downloadsolc] > cd node_modules/solc && (test -e soljson.js || wget https://ethereum.github.io/solc-bin/soljson.js) && cd ..
[downloadsolc] 
[downloadsolc] sh: wget: command not found
[downloadsolc] npm ERR! file sh
[downloadsolc] npm ERR! code ELIFECYCLE
[downloadsolc] npm ERR! errno ENOENT
[downloadsolc] npm ERR! syscall spawn
[downloadsolc] npm ERR! remix-solidity@0.0.8 downloadsolc: `cd node_modules/solc && (test -e soljson.js || wget https://ethereum.github.io/solc-bin/soljson.js) && cd ..`
[downloadsolc] npm ERR! spawn ENOENT
[downloadsolc] npm ERR! 
[downloadsolc] npm ERR! Failed at the remix-solidity@0.0.8 downloadsolc script.
[downloadsolc] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[downloadsolc] 
[downloadsolc] npm ERR! A complete log of this run can be found in:
[downloadsolc] npm ERR!     /Users/xxxx/.npm/_logs/2018-02-08T06_45_36_324Z-debug.log
ERROR: "downloadsolc" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-solidity@0.0.8 postinstall: `npm-run-all -ls downloadsolc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-solidity@0.0.8 postinstall script.
```

**Comment by iurimatias** [comment]
@jiashunran can you retry and see if you are still having this issue? there was an issue with downloading solc that we fixed last week so this might be ok now

**Comment by liamaharon** [comment]
@iurimatias I'm still having an issue downloading solc
```
[downloadsolc] 
[downloadsolc] > remix-solidity@0.0.8 downloadsolc /home/liam/Github/remix-ide/node_modules/remix-solidity
[downloadsolc] > cd node_modules/solc && (test -e soljson.js || wget https://ethereum.github.io/solc-bin/soljson.js) && cd ..
[downloadsolc] 
[downloadsolc] --2018-02-25 10:53:07--  https://ethereum.github.io/solc-bin/soljson.js
[downloadsolc] Resolving ethereum.github.io (ethereum.github.io)... 2a04:4e42:13::403, 151.101.81.147
[downloadsolc] Connecting to ethereum.github.io (ethereum.github.io)|2a04:4e42:13::403|:443... connected.
[downloadsolc] Unable to establish SSL connection.
[downloadsolc] 
[downloadsolc] npm ERR! Linux 4.13.0-32-generic
[downloadsolc] npm ERR! argv "/home/liam/.nvm/versions/node/v7.10.1/bin/node" "/home/liam/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/npm-cli.js" "run" "downloadsolc"
[downloadsolc] npm ERR! node v7.10.1
[downloadsolc] npm ERR! npm  v4.2.0
[downloadsolc] npm ERR! code ELIFECYCLE
[downloadsolc] npm ERR! errno 4
[downloadsolc] npm ERR! remix-solidity@0.0.8 downloadsolc: `cd node_modules/solc && (test -e soljson.js || wget https://ethereum.github.io/solc-bin/soljson.js) && cd ..`
[downloadsolc] npm ERR! Exit status 4
[downloadsolc] npm ERR! 
[downloadsolc] npm ERR! Failed at the remix-solidity@0.0.8 downloadsolc script 'cd node_modules/solc && (test -e soljson.js || wget https://ethereum.github.io/solc-bin/soljson.js) && cd ..'.
[downloadsolc] npm ERR! Make sure you have the latest version of node.js and npm installed.
[downloadsolc] npm ERR! If you do, this is most likely a problem with the remix-solidity package,
[downloadsolc] npm ERR! not with npm itself.
[downloadsolc] npm ERR! Tell the author that this fails on your system:
[downloadsolc] npm ERR!     cd node_modules/solc && (test -e soljson.js || wget https://ethereum.github.io/solc-bin/soljson.js) && cd ..
[downloadsolc] npm ERR! You can get information on how to open an issue for this project with:
[downloadsolc] npm ERR!     npm bugs remix-solidity
[downloadsolc] npm ERR! Or if that isn't available, you can get their info via:
[downloadsolc] npm ERR!     npm owner ls remix-solidity
[downloadsolc] npm ERR! There is likely additional logging output above.
[downloadsolc] 
[downloadsolc] npm ERR! Please include the following file with any support request:
[downloadsolc] npm ERR!     /home/liam/.npm/_logs/2018-02-24T23_53_07_309Z-debug.log
ERROR: "downloadsolc" exited with 4.
```

Full log:
[2018-02-24T23_53_09_371Z-debug.log](https://github.com/ethereum/remix-ide/files/1755458/2018-02-24T23_53_09_371Z-debug.log)

**Comment by Dracarys** [comment]
@jiashunran Install wget

**Comment by yann300** [comment]
closing now, please reopen if necessary

**Comment by jackbonaguro** [comment]
Can you reopen? The same thing happened to me and I have wget installed on
Ubuntu 16.04

**Comment by ndsun** [comment]
whene I excute npm install,this log shows 
[build            ] 
[build            ] > remix-ide@0.6.4-alpha.1 build /opt/remix/remix-ide
[build            ] > browserify src/index.js -o build/app.js
[build            ] 
[build            ] Error: Cannot find module './soljson.js' from '/opt/remix/remix-ide/remix/remix-solidity/node_modules/solc'
[build            ]     at /opt/remix/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
[build            ]     at load (/opt/remix/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
[build            ]     at onex (/opt/remix/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
[build            ]     at /opt/remix/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
[build            ]     at FSReqWrap.oncomplete (fs.js:114:15)
what is the reason for this?

**Comment by LianaHus** [comment]
@yann300

**Comment by yann300** [comment]
this should be fixed by now, please reopen if not
