### ISSUE TITLE
npm install giving errors

### ISSUE THREAD

**Issue by aatiranum** [ethereum/remix-ide#1216]
I am installing remix-ide using the following commands
git clone https://github.com/ethereum/remix-ide.git
cd remix-ide
npm install

on Ubuntu 16.04

But npm install is giving error. Following is the log file generated.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle remix-ide@0.6.1-alpha.4~prebuild: remix-ide@0.6.1-alpha.4
6 info lifecycle remix-ide@0.6.1-alpha.4~build: remix-ide@0.6.1-alpha.4
7 verbose lifecycle remix-ide@0.6.1-alpha.4~build: unsafe-perm in lifecycle true
8 verbose lifecycle remix-ide@0.6.1-alpha.4~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Documents/remix-ide/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Documents/remix-ide/node_modules/.bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle remix-ide@0.6.1-alpha.4~build: CWD: /home/user/Documents/remix-ide
10 silly lifecycle remix-ide@0.6.1-alpha.4~build: Args: [ '-c', 'browserify src/index.js -o build/app.js' ]
11 silly lifecycle remix-ide@0.6.1-alpha.4~build: Returned: code: 1  signal: null
12 info lifecycle remix-ide@0.6.1-alpha.4~build: Failed to exec build script
13 verbose stack Error: remix-ide@0.6.1-alpha.4 build: `browserify src/index.js -o build/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid remix-ide@0.6.1-alpha.4
15 verbose cwd /home/user/Documents/remix-ide
16 verbose Linux 4.13.0-37-generic
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error remix-ide@0.6.1-alpha.4 build: `browserify src/index.js -o build/app.js`
22 error Exit status 1
23 error Failed at the remix-ide@0.6.1-alpha.4 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Please help.

**Comment by bitpshr** [comment]
This is due to MatAtBread/fast-async#53. This issue should resolve itself once a fix is implemented upstream.

As a temporary workaround, you can manually install the missing dependency:

```
git clone https://github.com/ethereum/remix-ide.git
cd remix-ide
npm i @babel/helper-module-imports
npm i
```
