### ISSUE TITLE
remin-ide安装错误

### ISSUE THREAD

**Issue by fishtx** [ethereum/remix-ide#1220]
> browserify src/index.js -o build/app.js

Error: Cannot find module '@babel/helper-module-imports' while parsing file: /root/ethereum/remix-ide/src/index.js
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at module.exports (/root/ethereum/remix-ide/node_modules/fast-async/plugin.js:10:25)
    at Function.memoisePluginContainer (/root/ethereum/remix-ide/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/root/ethereum/remix-ide/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /root/ethereum/remix-ide/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/root/ethereum/remix-ide/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! remix-ide@0.6.1-alpha.4 build: `browserify src/index.js -o build/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-ide@0.6.1-alpha.4 build script 'browserify src/index.js -o build/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remix-ide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify src/index.js -o build/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remix-ide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remix-ide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ethereum/remix-ide/npm-debug.log

**Comment by yann300** [comment]
have you run `npm install` before?

**Comment by fishtx** [comment]
@yann300 yse, I do

**Comment by apa7** [comment]
+1
