### ISSUE TITLE
can not install the pack

### ISSUE THREAD

**Issue by kk412027247** [ethereum/remix-ide#1271]
### when i run 'sudo npm install remix-ide -g' and get the error.

could somebody help me ? 

```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/ethereum/remixd.git /home/kk412027247/.npm/_cacache/tmp/git-clone-d021abdc
npm ERR! /home/kk412027247/.npm/_cacache/tmp/git-clone-d021abdc/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kk412027247/.npm/_logs/2018-04-20T16_07_09_218Z-debug.log
```
#### debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'remix-ide', '-g' ]
2 info using npm@5.8.0
3 info using node@v9.11.1
4 verbose npm-session 2102723314173797
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/remix-ide 1255ms (from cache)
8 silly pacote tag manifest for remix-ide@latest fetched in 1339ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule remix-ide@0.6.2 checking installable status
14 silly removeObsoleteDep removing remix-ide from the tree as its been replaced by a newer version or is no longer required
15 http fetch GET 304 https://registry.npmjs.org/http-server 271ms (from cache)
16 silly pacote version manifest for http-server@0.9.0 fetched in 277ms
17 silly resolveWithNewModule http-server@0.9.0 checking installable status
18 silly fetchPackageMetaData error for remixd@git+https://github.com/ethereum/remixd.git Command failed: /usr/bin/git clone -q https://github.com/ethereum/remixd.git /home/kk412027247/.npm/_cacache/tmp/git-clone-d021abdc
18 silly fetchPackageMetaData /home/kk412027247/.npm/_cacache/tmp/git-clone-d021abdc/.git: Permission denied
19 verbose stack Error: Command failed: /usr/bin/git clone -q https://github.com/ethereum/remixd.git /home/kk412027247/.npm/_cacache/tmp/git-clone-d021abdc
19 verbose stack /home/kk412027247/.npm/_cacache/tmp/git-clone-d021abdc/.git: Permission denied
19 verbose stack
19 verbose stack     at ChildProcess.exithandler (child_process.js:273:12)
19 verbose stack     at ChildProcess.emit (events.js:180:13)
19 verbose stack     at maybeClose (internal/child_process.js:936:16)
19 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
20 verbose cwd /home/kk412027247
21 verbose Linux 4.4.0-43-Microsoft
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "remix-ide" "-g"
23 verbose node v9.11.1
24 verbose npm  v5.8.0
25 error code 1
26 error Command failed: /usr/bin/git clone -q https://github.com/ethereum/remixd.git /home/kk412027247/.npm/_cacache/tmp/git-clone-d021abdc
26 error /home/kk412027247/.npm/_cacache/tmp/git-clone-d021abdc/.git: Permission denied
27 verbose exit [ 1, true ]
```

**Comment by yann300** [comment]
.hmm you got a `permission denied` even though you run with sudo. trying perhaps reinstalling `.npm`

**Comment by kk412027247** [comment]
@yann300  thanks, it work.

**Comment by xuanluo2016** [comment]
tried npm 5.6 and 6.0.1 with command:
sudo npm install remix-ide -g
and both failed with error: /.npm/_cacache/tmp/git-clone-91f2d684/.git: Permission denied

workaround:
downgrade npm to 4 by: sudo npm install -g npm@4
and then try installing remix again. this works for me.

**Comment by gravyplaya** [comment]
This should not be a solution. Make the package compatible with latest npm.
