### ISSUE TITLE
Error while installing remix-ide in windows

### ISSUE THREAD

**Issue by sugalivijaychari** [ethereum/remix-ide#1302]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>node -v
v8.11.1

C:\Windows\system32>npm -v
5.6.0

C:\Windows\system32>npm install npm@latest -g
C:\Users\Vijay\AppData\Roaming\npm\npm -> C:\Users\Vijay\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\Vijay\AppData\Roaming\npm\npx -> C:\Users\Vijay\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
+ npm@6.0.0
added 680 packages in 162.04s

C:\Windows\system32>npm login
Username: sugalivijaychari
Password:
Email: (this IS public) sugalivijaychari@gmail.com
Logged in as sugalivijaychari on https://registry.npmjs.org/.

C:\Windows\system32>npm install remix-ide -g
C:\Users\Vijay\AppData\Roaming\npm\remix-ide -> C:\Users\Vijay\AppData\Roaming\npm\node_modules\remix-ide\bin\remix-ide
+ remix-ide@0.6.3
added 1 package from 1 contributor in 59.371s

C:\Windows\system32>remix-ide
module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Windows\system32\remix-ide\node_modules\scrypt\index.js:3:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Windows\system32\remix-ide\node_modules\scrypt.js\node.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Windows\system32\remix-ide\node_modules\web3-eth-accounts\src\index.js:35:16)
    at Module._compile (module.js:652:30)

**Comment by HappyITWala** [comment]
Just wondering if there is a workaround by changing the config so that remix should pick the path of scrypt from given location?

Error - Cannot find module './build/Release/scrypt'
Scrypt as well as Remix are here on my PC - MYfolder\npm\node_modules\

**Comment by HappyITWala** [comment]
Workaround worked for me.  Copied MYfolder\npm\node_modules\scrypt\build to MYfolder\npm\node_modules\remix-de\node_modules\scrypt (Or create shortcut)
