### ISSUE TITLE
Max Call Stack Exceeded on npm run prepublish

### ISSUE THREAD

**Issue by ansermino** [ethereum/remix-ide#1373]
I am getting an error when running `npm run prepublish`, which is called by `npm install`. I am running Ubuntu 16.04 and Node 8.9.4. I have tried from a fresh clone with no success.

```
[build            ] 
[build            ] > remix-ide@0.6.3 build /home/david/dev/remix-ide
[build            ] > browserify src/index.js -o build/app.js
[build            ] 
[build            ] SyntaxError: Maximum call stack size exceeded while parsing /home/david/dev/remix-ide/node_modules/remix-solidity/node_modules/solc/soljson.js while parsing file: /home/david/dev/remix-ide/node_modules/remix-solidity/node_modules/solc/soljson.js
[build            ]     at DestroyableTransform.end [as _flush] (/home/david/dev/remix-ide/node_modules/insert-module-globals/index.js:114:21)
[build            ]     at DestroyableTransform.prefinish (/home/david/dev/remix-ide/node_modules/readable-stream/lib/_stream_transform.js:138:10)
[build            ]     at emitNone (events.js:106:13)
[build            ]     at DestroyableTransform.emit (events.js:208:7)
[build            ]     at prefinish (/home/david/dev/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:619:14)
[build            ]     at finishMaybe (/home/david/dev/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:627:5)
[build            ]     at endWritable (/home/david/dev/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:638:3)
[build            ]     at DestroyableTransform.Writable.end (/home/david/dev/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:594:41)
[build            ]     at DestroyableTransform.onend (/home/david/dev/remix-ide/node_modules/readable-stream/lib/_stream_readable.js:577:10)
[build            ]     at Object.onceWrapper (events.js:313:30)
[build            ] npm ERR! code ELIFECYCLE
[build            ] npm ERR! errno 1
[build            ] npm ERR! remix-ide@0.6.3 build: `browserify src/index.js -o build/app.js`
[build            ] npm ERR! Exit status 1
[build            ] npm ERR! 
[build            ] npm ERR! Failed at the remix-ide@0.6.3 build script.
[build            ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[build            ] 
[build            ] npm ERR! A complete log of this run can be found in:
[build            ] npm ERR!     /home/david/.npm/_logs/2018-06-19T20_04_00_607Z-debug.log
```

**Comment by ansermino** [comment]
Solved by switching to node 9.11.2

**Comment by willdeuschle** [comment]
Anything else you did to fix this?

**Comment by fr0zenrain** [comment]
macos 10.12 node 10.6 seems not ok
