### ISSUE TITLE
Something Error when run `npm install` on Mac OS

### ISSUE THREAD

**Issue by wuzhitian** [ethereum/remix-ide#1411]
```
[build            ]
[build            ] > remix-ide@0.6.4 build /Users/user/Applications/remix-ide
[build            ] > browserify src/index.js -o build/app.js
[build            ]
[build            ] SyntaxError: Maximum call stack size exceeded while parsing /Users/user/Applications/remix-ide/node_modules/remix-solidity/node_modules/solc/soljson.js while parsing file: /Users/user/Applications/remix-ide/node_modules/remix-solidity/node_modules/solc/soljson.js
[build            ]     at DestroyableTransform.end [as _flush] (/Users/user/Applications/remix-ide/node_modules/insert-module-globals/index.js:114:21)
[build            ]     at DestroyableTransform.prefinish (/Users/user/Applications/remix-ide/node_modules/readable-stream/lib/_stream_transform.js:138:10)
[build            ]     at emitNone (events.js:106:13)
[build            ]     at DestroyableTransform.emit (events.js:208:7)
[build            ]     at prefinish (/Users/user/Applications/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:619:14)
[build            ]     at finishMaybe (/Users/user/Applications/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:627:5)
[build            ]     at endWritable (/Users/user/Applications/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:638:3)
[build            ]     at DestroyableTransform.Writable.end (/Users/user/Applications/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:594:41)
[build            ]     at DestroyableTransform.onend (/Users/user/Applications/remix-ide/node_modules/readable-stream/lib/_stream_readable.js:577:10)
[build            ]     at Object.onceWrapper (events.js:313:30)
[build            ] npm ERR! code ELIFECYCLE
[build            ] npm ERR! errno 1
[build            ] npm ERR! remix-ide@0.6.4 build: `browserify src/index.js -o build/app.js`
[build            ] npm ERR! Exit status 1
[build            ] npm ERR!
[build            ] npm ERR! Failed at the remix-ide@0.6.4 build script.
[build            ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[build            ]
[build            ] npm ERR! A complete log of this run can be found in:
```

**Comment by Yammmy** [comment]
upgraded to 9 still got this err below...
```
ERROR: "build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.6.4 prepublish: `mkdirp build; npm-run-all -ls downloadsolc_root build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remix-ide@0.6.4 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-07-28T01_33_01_000Z-debug.log
 ✘  ⮀ ~/learn-sth/solidityProject/remix-ide ⮀ ⭠ master ⮀ node -v
v9.0.0
```

**Comment by yann300** [comment]
we are going to push an update pretty soon

**Comment by yann300** [comment]
that is fixed now. could you pull and retry please?
