### ISSUE TITLE
npm run build error-'support-tab.js'

### ISSUE THREAD

**Issue by skykingit** [ethereum/remix-ide#1714]
After npm install
i run 'npm run build',then the console show error as below:

sh-3.2# npm run build

> remix-ide@0.7.5 build /Users/skykingit/Documents/pchain/ethereum/remix-ide-master
> browserify src/index.js -o build/app.js --exclude solc

Error: /Users/skykingit/Documents/pchain/ethereum/remix-ide-master/src/app/tabs/support-tab.js: multiple root elements must be wrapped in an enclosing tag
    at /Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/hyperx/index.js:153:13
    at yoyoify (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-plugin-yo-yoify/index.js:173:36)
    at PluginPass.TaggedTemplateExpression (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-plugin-yo-yoify/index.js:331:27)
    at newFn (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/skykingit/Documents/pchain/ethereum/remix-ide-master/node_modules/babel-traverse/lib/context.js:192:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.7.5 build: `browserify src/index.js -o build/app.js --exclude solc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-ide@0.7.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2019-02-21T09_41_03_757Z-debug.log

why the 'support-tab.js ' have error????

**Comment by yann300** [comment]
that is fixed in `swap_it`, the current develop branch
