### ISSUE TITLE
Error when installing using NPM (Ubuntu)

### ISSUE THREAD

**Issue by TravelingTechGuy** [ethereum/remix-ide#2083]
I'm trying to install using NPM. My environment:

**OS**: Ubuntu 18.04.2 LTS running under WSL (Windows 10 Pro)
**Node**: 12.4.0
**NPM**: 6.9.0
**Python**: 2.7.15+
Latest `build-essentials` installed, and NPM rebuilt, per instructions.

I'm getting the following errors:

```bash
guy@Phoenix:~$ npm install remix-ide -g
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall /home/guy/.npm-global/lib/node_modules/remix-ide/node_modules/scrypt
> node node-scrypt-preinstall.js

/home/guy/.npm-global/bin/remix-ide -> /home/guy/.npm-global/lib/node_modules/remix-ide/bin/remix-ide

> scrypt@6.0.3 install /home/guy/.npm-global/lib/node_modules/remix-ide/node_modules/scrypt
> node-gyp rebuild

make: Entering directory '/home/guy/.npm-global/lib/node_modules/remix-ide/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
  AR(target) Release/obj.target/scrypt_lib.a
  COPY Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h: In constructor ‘NodeScrypt::Params::Params(const v8::Local<v8::Object>&)’:
../src/node-boilerplate/inc/scrypt_common.h:39:48: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
                                                ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/guy/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/guy/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:3412:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                       ^
/home/guy/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:39:63: error: no matching function for call to ‘v8::Value::Uint32Value()’
       N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
                                                               ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2567:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:40:48: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       r(obj->Get(Nan::New("r").ToLocalChecked())->Uint32Value()),
                                                ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/guy/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/guy/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:3412:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                       ^
/home/guy/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:40:63: error: no matching function for call to ‘v8::Value::Uint32Value()’
       r(obj->Get(Nan::New("r").ToLocalChecked())->Uint32Value()),
                                                               ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2567:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:41:48: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       p(obj->Get(Nan::New("p").ToLocalChecked())->Uint32Value()) {}
                                                ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/guy/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/guy/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:3412:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                       ^
/home/guy/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:41:63: error: no matching function for call to ‘v8::Value::Uint32Value()’
       p(obj->Get(Nan::New("p").ToLocalChecked())->Uint32Value()) {}
                                                               ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2567:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:0,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_async.h: In member function ‘virtual void ScryptAsyncWorker::HandleErrorCallback()’:
../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
       callback->Call(1, argv);
                             ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
../src/node-boilerplate/inc/scrypt_params_async.h: In constructor ‘ScryptParamsAsyncWorker::ScryptParamsAsyncWorker(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node-boilerplate/inc/scrypt_params_async.h:35:36: error: no matching function for call to ‘v8::Value::NumberValue()’
       maxtime(info[0]->NumberValue()),
                                    ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2564:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
../src/node-boilerplate/inc/scrypt_params_async.h:36:39: error: no matching function for call to ‘v8::Value::NumberValue()’
       maxmemfrac(info[1]->NumberValue()),
                                       ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2564:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
../src/node-boilerplate/inc/scrypt_params_async.h:37:36: error: no matching function for call to ‘v8::Value::IntegerValue()’
       maxmem(info[2]->IntegerValue()),
                                    ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2565:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
../src/node-boilerplate/inc/scrypt_params_async.h:38:39: error: no matching function for call to ‘v8::Value::IntegerValue()’
       osfreemem(info[3]->IntegerValue())
                                       ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2565:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/home/guy/.node-gyp/12.4.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
../src/node-boilerplate/scrypt_params_async.cc: In member function ‘virtual void ScryptParamsAsyncWorker::HandleOKCallback()’:
../src/node-boilerplate/scrypt_params_async.cc:23:67: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   obj->Set(Nan::New("N").ToLocalChecked(), Nan::New<Integer>(logN));
                                                                   ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/guy/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/guy/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/guy/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:24:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   obj->Set(Nan::New("r").ToLocalChecked(), Nan::New<Integer>(r));
                                                                ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/guy/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/guy/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/guy/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:25:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   obj->Set(Nan::New("p").ToLocalChecked(), Nan::New<Integer>(p));
                                                                ^
In file included from /home/guy/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/guy/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/guy/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/guy/.node-gyp/12.4.0/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/guy/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:32:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) cons ’ is deprecated [-Wdeprecated-declarations]
   callback->Call(2, argv);
                         ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
scrypt.target.mk:127: recipe for target 'Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o' failed
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
make: Leaving directory '/home/guy/.npm-global/lib/node_modules/remix-ide/node_modules/scrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-17763-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/guy/.npm-global/lib/node_modules/remix-ide/node_modules/scrypt
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/remix-ide/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guy/.npm/_logs/2019-06-13T15_13_13_592Z-debug.log
```

I tried to manually install `node-gyp` globally (which sometimes helps with compiled code) and got the same results.

**Comment by geethagurram21** [comment]
#2466

**Comment by xiaods** [comment]
@TravelingTechGuy  please use node v10.x for compatible

**Comment by TravelingTechGuy** [comment]
@xiaods I'm on Node 13.5 right now. Any specific reason that would require v10?

**Comment by xiaods** [comment]
@TravelingTechGuy because the remix project is testing on node v10. it have not yet work on node 13.x branch.

**Comment by sespaces** [comment]
I also ran into these issues. I eventually succeed with Ubuntu 18.04 and 18.10.
Here is a write-up: https://github.com/sespaces/remix-ide-server-hosting/blob/master/remix-ide-installation-ubuntu-18.md

**Comment by xiaods** [comment]
@sespaces you can use nvm to change the nodejs version. it is easy.
