### ISSUE TITLE
Failed to install remix-ide

### ISSUE THREAD

**Issue by caiyesd** [ethereum/remix-ide#2466]
I ran `npm install remix-ide -g` but it failed to be installed.

My npm and node version.
```
~/Downloads/remix-ide$ npm --version
6.13.1
~/Downloads/remix-ide$ node --version
v12.13.1
```
Logs
```
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
scrypt.target.mk:129: recipe for target 'Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o' failed
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
make: Leaving directory '/home/jiangxin/.node_modules/lib/node_modules/remix-ide/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jiangxin/.node_modules/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-70-generic
gyp ERR! command "/usr/local/bin/node" "/home/jiangxin/.node_modules/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jiangxin/.node_modules/lib/node_modules/remix-ide/node_modules/scrypt
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/remix-ide/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jiangxin/.npm/_logs/2019-12-03T03_55_08_569Z-debug.log
```

**Comment by bmcd87** [comment]
I had similar errors when I was using the wrong version of node. Try switching to node 10.16.0 (i use [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md) to switch between versions)

**Comment by xiaods** [comment]
use v10.16 to compatible remix.

**Comment by xiaods** [comment]
please close this issue.

**Comment by klavatron** [comment]
have the same issue with 10.16.0

**Comment by sespaces** [comment]
I also ran into these issues. I eventually succeed with Ubuntu 18.04 and 18.10.
Here is a write-up: https://github.com/sespaces/remix-ide-server-hosting/blob/master/remix-ide-installation-ubuntu-18.md

**Comment by iceqing** [comment]
thansks@xiaods !

```
nvm use v10.16.2
```

This solved my problem.

But v10.18.1and v12.14.1 or other version get same problem

**Comment by hilmarx** [comment]
works very nicely.
