### ISSUE TITLE
Can't install remix-ide using npm install

### ISSUE THREAD

**Issue by ottpeter** [ethereum/remix-ide#2624]
node -v:` v10.16.0`
This is the error I get:

```
ERROR: "build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.9.4 prepublish: `mkdirp build; npm-run-all -ls downloadsolc_root build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-ide@0.9.4 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-02-24T10_31_22_630Z-debug.log

```

**Comment by yann300** [comment]
could you run it in verbose mode?
In the meantime, please have a look to https://github.com/ethereum/remix-desktop/releases

**Comment by ottpeter** [comment]
```
  100%  310K=22s
[downloadsolc_root] 
[downloadsolc_root] 2020-02-26 15:14:19 (584 KB/s) - ‘soljson.js’ saved [12849836/12849836]
[downloadsolc_root] 
[downloadsolc_root] npm verb lifecycle remix-ide@0.9.4~downloadsolc_root: unsafe-perm in lifecycle true
[downloadsolc_root] npm verb lifecycle remix-ide@0.9.4~downloadsolc_root: PATH: /home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Remix/node_modules/.bin:/home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Remix/node_modules/.bin:/home/user/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
[downloadsolc_root] npm verb lifecycle remix-ide@0.9.4~downloadsolc_root: CWD: /home/user/Remix
[downloadsolc_root] npm info lifecycle remix-ide@0.9.4~postdownloadsolc_root: remix-ide@0.9.4
[downloadsolc_root] npm verb exit [ 0, true ]
[downloadsolc_root] npm timing npm Completed in 24356ms
[downloadsolc_root] npm info ok 
[build            ] npm info it worked if it ends with ok
[build            ] npm verb cli [
[build            ] npm verb cli   '/home/user/.nvm/versions/node/v12.14.1/bin/node',
[build            ] npm verb cli   '/home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/bin/npm-cli.js',
[build            ] npm verb cli   'run',
[build            ] npm verb cli   'build'
[build            ] npm verb cli ]
[build            ] npm info using npm@6.13.4
[build            ] npm info using node@v12.14.1
[build            ] npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
[build            ] npm info lifecycle remix-ide@0.9.4~prebuild: remix-ide@0.9.4
[build            ] npm info lifecycle remix-ide@0.9.4~build: remix-ide@0.9.4
[build            ] 
[build            ] > remix-ide@0.9.4 build /home/user/Remix
[build            ] > browserify src/index.js -o build/app.js --exclude solc
[build            ] 
[build            ] Error: Cannot find module '/home/user/Remix/src/index.js' from '/home/user/Remix'
[build            ]     at /home/user/Remix/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
[build            ]     at load (/home/user/Remix/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
[build            ]     at onex (/home/user/Remix/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
[build            ]     at /home/user/Remix/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
[build            ]     at FSReqCallback.oncomplete (fs.js:158:21)
[build            ] npm verb lifecycle remix-ide@0.9.4~build: unsafe-perm in lifecycle true
[build            ] npm verb lifecycle remix-ide@0.9.4~build: PATH: /home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Remix/node_modules/.bin:/home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Remix/node_modules/.bin:/home/user/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
[build            ] npm verb lifecycle remix-ide@0.9.4~build: CWD: /home/user/Remix
[build            ] npm info lifecycle remix-ide@0.9.4~build: Failed to exec build script
[build            ] npm verb stack Error: remix-ide@0.9.4 build: `browserify src/index.js -o build/app.js --exclude solc`
[build            ] npm verb stack Exit status 1
[build            ] npm verb stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
[build            ] npm verb stack     at EventEmitter.emit (events.js:223:5)
[build            ] npm verb stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
[build            ] npm verb stack     at ChildProcess.emit (events.js:223:5)
[build            ] npm verb stack     at maybeClose (internal/child_process.js:1021:16)
[build            ] npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[build            ] npm verb pkgid remix-ide@0.9.4
[build            ] npm verb cwd /home/user/Remix
[build            ] npm verb Linux 4.19.94-1.pvops.qubes.x86_64
[build            ] npm verb argv "/home/user/.nvm/versions/node/v12.14.1/bin/node" "/home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/bin/npm-cli.js" "run" "build"
[build            ] npm verb node v12.14.1
[build            ] npm verb npm  v6.13.4
[build            ] npm ERR! code ELIFECYCLE
[build            ] npm ERR! errno 1
[build            ] npm ERR! remix-ide@0.9.4 build: `browserify src/index.js -o build/app.js --exclude solc`
[build            ] npm ERR! Exit status 1
[build            ] npm ERR! 
[build            ] npm ERR! Failed at the remix-ide@0.9.4 build script.
[build            ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[build            ] npm verb exit [ 1, true ]
[build            ] npm timing npm Completed in 347ms
[build            ] 
[build            ] npm ERR! A complete log of this run can be found in:
[build            ] npm ERR!     /home/user/.npm/_logs/2020-02-26T14_14_20_491Z-debug.log
ERROR: "build" exited with 1.
npm verb lifecycle remix-ide@0.9.4~prepublish: unsafe-perm in lifecycle true
npm verb lifecycle remix-ide@0.9.4~prepublish: PATH: /home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Remix/node_modules/.bin:/home/user/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
npm verb lifecycle remix-ide@0.9.4~prepublish: CWD: /home/user/Remix
npm timing audit submit Completed in 2023ms
npm http fetch POST 200 http://registry.npmjs.org/-/npm/v1/security/audits/quick 2110ms
npm timing audit body Completed in 88ms
npm info lifecycle remix-ide@0.9.4~prepublish: Failed to exec prepublish script
npm verb stack Error: remix-ide@0.9.4 prepublish: `mkdirp build; npm-run-all -ls downloadsolc_root build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:223:5)
npm verb stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:223:5)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm verb pkgid remix-ide@0.9.4
npm verb cwd /home/user/Remix
npm verb Linux 4.19.94-1.pvops.qubes.x86_64
npm verb argv "/home/user/.nvm/versions/node/v12.14.1/bin/node" "/home/user/.nvm/versions/node/v12.14.1/bin/npm" "install" "--verbose"
npm verb node v12.14.1
npm verb npm  v6.13.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.9.4 prepublish: `mkdirp build; npm-run-all -ls downloadsolc_root build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-ide@0.9.4 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 33680ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-02-26T14_14_20_566Z-debug.log

```

**Comment by LianaHus** [comment]
@yann300
