### ISSUE TITLE
transfer built remix-ide to non-internet connected machine

### ISSUE THREAD

**Issue by dragoonduel** [ethereum/remix-ide#2959]
Hi,

i want to host the remix-ide on my server as there are some network restrictions for us on using it online. 
my servers are also no connected to the internet. 

I managed to download and npm install it on another machine that has internet. 

Is it possible for me to just tar.gz the whole folder, and use it directly on my non-internet connected server?

i tried to do so but when i run npm start it is giving me an error 

the npm install is done on nodejs version 1v0.16.2
the nodejs that is on my non-internet connected server is also v10.16.2

this is the error that i am getting after running npm start after uncompress on my server

0 info it worked if it ends with ok
1 verbose cli [ '/node/node-v10.16.2/bin/node',
1 verbose cli   '/node/node-v10.16.2/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle remix-ide@0.10.3~prestart: remix-ide@0.10.3
6 info lifecycle remix-ide@0.10.3~start: remix-ide@0.10.3
7 verbose lifecycle remix-ide@0.10.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle remix-ide@0.10.3~start: PATH: /node/node-v10.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/node/remix-master/node_modules/.bin:/node/jdk-14.0.1/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/user1/.local/bin:/home/user1/bin:/node/jdk-14.0.1/bin:/node/besu-1.4.6/bin:/node/node3/orion-1.4.0/bin:/node/node-v10.16.2/bin
9 verbose lifecycle remix-ide@0.10.3~start: CWD: /node/remix-master
10 silly lifecycle remix-ide@0.10.3~start: Args: [ '-c', 'npm-run-all -lpr serve watch onchange remixd' ]
11 info lifecycle remix-ide@0.10.3~start: Failed to exec start script
12 verbose stack Error: remix-ide@0.10.3 start: `npm-run-all -lpr serve watch onchange remixd`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/node/node-v10.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid remix-ide@0.10.3
14 verbose cwd /node/remix-master
15 verbose Linux 3.10.0-1062.26.1.el7.x86_64
16 verbose argv "/node/node-v10.16.2/bin/node" "/node/node-v10.16.2/bin/npm" "start"
17 verbose node v10.16.2
18 verbose npm  v6.9.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error remix-ide@0.10.3 start: `npm-run-all -lpr serve watch onchange remixd`
23 error spawn ENOENT
24 error Failed at the remix-ide@0.10.3 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by yann300** [comment]
can you try to install remix-desktop? https://github.com/ethereum/remix-desktop/releases/tag/v1.0.7
