### ISSUE TITLE
Error when attempting to start the remix IDE for the first time: Error: Cannot find module 'remixd'

### ISSUE THREAD

**Issue by intmainvoid** [ethereum/remix-ide#2970]
Installed remix-ide on MacOS using:
```
> npm install remix-ide -g
```
Seemed to install ok
```
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
/Users/blah/.nvm/versions/node/v12.13.1/bin/remix-ide -> /Users/blah/.nvm/versions/node/v12.13.1/lib/node_modules/remix-ide/bin/remix-ide
+ remix-ide@0.10.3
added 173 packages from 183 contributors in 36.126s
```
However, when I attempt to run it for the first time I get the following error:
```
> remix-ide
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'remixd'
Require stack:
- /Users/blah/.nvm/versions/node/v12.13.1/lib/node_modules/remix-ide/bin/remix-ide
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/blah/.nvm/versions/node/v12.13.1/lib/node_modules/remix-ide/bin/remix-ide:4:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/blah/.nvm/versions/node/v12.13.1/lib/node_modules/remix-ide/bin/remix-ide'
  ]
}
```
MacOS version 10.15.6
npm version: 6.14.2
node version: v12.13.1

How can I get Remix IDE working on my Mac?

**Comment by yann300** [comment]
using the npm module has been deprecated. If you want to run remix locally, please use https://github.com/ethereum/remix-desktop/releases instead

**Comment by yann300** [comment]
alternatively you can also run it in a Docker https://twitter.com/EthereumRemix/status/1286331517707444225

**Comment by Ankarrr** [comment]
I think the doc should be updated!
